[package]
name = "amuse_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amuse_event = { path = "../amuse_event" }
askama = "0.7.2"
syn = "0.15.23"
quote = "0.6.10"

[lib]
proc-macro = true